---
catalog_name: mlops_dev
schema_name: ateyatec
experiment_name_basic: /Shared/wine-quality-basic
experiment_name_custom: /Shared/wine-quality-custom
experiment_name_fe: /Shared/wine-quality-fe

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - alcohol
  - density
  - volatile_acidity
  - chlorides
  - residual_sugar
  - free_sulfur_dioxide
  - pH
  - total_sulfur_dioxide
  - sulphates
  - citric_acid
  - fixed_acidity

cat_features:
  - type

target: quality
