catalog_name: mlops_dev
schema_name: ateyatec

parameters:
  learning_rate: 0.01
  n_stimators: 1000
  max_depth: 6

num_features:
  - alcohol
  - density
  - volatile_acidity
  - chlorides
  - residual_sugar
  - free_sulfur_dioxide
  - pH
  - total_sulfur_dioxide
  - sulphates
  - citric_acid
  - fixed_acidity

cat_features:
  - type

target: quality
