---
prd:
  catalog_name: ws_mlops
  schema_name: wine_schema
  pipeline_id: 1818db79-f551-49bb-ad4f-f61cac9d91fc
acc:
  catalog_name: ws_mlops
  schema_name: wine_schema
  pipeline_id: 94748db79-f551-49bb-ad4f-f61cac9d91fc
dev:
  catalog_name: ws_mlops
  #schema_name: wine_quality
  schema_name: wine_schema
  pipeline_id: 0498db79-f551-49bb-ad4f-finac9d91fc

catalog_name: ws_mlops
schema_name: wine_schema
pipeline_id: 0498db79-f551-49bb-ad4f-finac9d91fc
experiment_name_basic: /Shared/wine-quality-basic
experiment_name_custom: /Shared/wine-quality-custom
experiment_name_fe: /Shared/wine-quality-fe

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

parameters_a:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

parameters_b:
  learning_rate: 0.02
  n_estimators: 1000
  max_depth: 5

num_features:
  - alcohol
  - density
  - volatile_acidity
  - chlorides
  - residual_sugar
  - free_sulfur_dioxide
  - pH
  - total_sulfur_dioxide
  - sulphates
  - citric_acid
  - fixed_acidity

cat_features:
  - type

target: quality
