---
name: CD Pipeline

on:
  push:
    branches:
      - "main"
      - "feature/*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read # No id-token required for service principal authentication

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

jobs:
  setup-validate:
    name: Set Up Environment
    runs-on: ubuntu-latest
    environment: dev # GitHub environment

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install UV
        uses: astral-sh/setup-uv@v1

      - name: Install Databricks CLI
        uses: databricks/setup-cli@948d7379a31615a4c8e9ccbbc5445a12d6b32736
        with:
          version: 0.221.1

      - name: Azure CLI Login with Service Principal
        uses: azure/login@v1
        with:
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ env.AZURE_CLIENT_ID }}
          client-secret: ${{ env.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL
          enable-AzPSSession: false

      - name: Set Databricks Token
        run: echo "DATABRICKS_TOKEN=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | jq .accessToken --raw-output)" >> $GITHUB_ENV

      - name: Deploy to Databricks
        env:
          DATABRICKS_BUNDLE_ENV: dev # Bundle target
        run: |
          databricks bundle deploy --var="git_sha=${{ github.sha }}"
          databricks bundle run wine-quality --var="git_sha=${{ github.sha }}"
