---
name: CD Pipeline

on:
  push:
    branches:
      - "main"
      - "feature/*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  setup-validate:
    name: Set Up Environment
    runs-on: ubuntu-latest
    environment: dev # GitHub environment

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install UV
        uses: astral-sh/setup-uv@v1

      - name: Install Databricks CLI
        uses: databricks/setup-cli@948d7379a31615a4c8e9ccbbc5445a12d6b32736
        with:
          version: 0.221.1

      - name: Azure CLI Login with Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build package
        run: |
          echo "Current working directory: $(pwd)"
          mkdir -p dist
          uv venv .venv
          source .venv/bin/activate
          uv pip install build
          python -m build --outdir dist
          echo "Build completed. Contents of 'dist':"
          ls -l dist

      - name: Deploy to Databricks
        env:
          DATABRICKS_BUNDLE_ENV: dev # Bundle target
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we're in the project root
          databricks bundle deploy --var="git_sha=${{ github.sha }}"
